//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variant2_Decor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public Materials()
        {
            this.ProductMaterials = new HashSet<ProductMaterials>();
        }
    
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public int MaterialTypeID { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal StockQuanity { get; set; }
        public decimal MinQuantity { get; set; }
        public decimal PackageQuantity { get; set; }
        public int UnitID { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual Units Units { get; set; }
        public virtual ICollection<ProductMaterials> ProductMaterials { get; set; }
    }
}
