//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Variant2_Decor.Models
{
    using System;
    using System.Collections.Generic;
    using Variant2_Decor.Function;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductMaterials = new HashSet<ProductMaterials>();
        }

        private float price;

        public int ProductID { get; set; }
        public int ProductTypeID { get; set; }
        public string ProductName { get; set; }
        public int Article { get; set; }
        public decimal MinPrice { get; set; }
        public decimal Width { get; set; }

        public float Price
        {
            get
            {
                price = CalculateProductPrice.GetPrice(this);
                return price;
            }
            set
            {
                price = value;
            }
        }

        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<ProductMaterials> ProductMaterials { get; set; }
    }
}
